<a href="https://colab.research.google.com/github/Mathin21/Medicine-Prediction-Using-Machine-Learning/blob/main/Mini_Project_Using_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# load dataset into pandas dataframe
import numpy as np
data= pd.read_csv('/content/Dataset1.csv')
data=data.iloc[:,0:6]
data

,Disease Type,Dosage,Age,Sex,Diagnosis Diabetes,Diagnosis Hypertension
0,Fever,250mg,45,Male,No,Yes
1,Diabetes,850mg,60,Female,Yes,No
2,Hypertension,400mg,55,Male,No,Yes
3,Headache,50mg,77,Male,Yes,Yes
4,Thyroid,100mcg,38,Female,No,No
...,...,...,...,...,...,...
245,Diabetes,850mg,62,Female,Yes,Yes
246,Vomiting,8mg,47,Female,Yes,Yes
247,Hypertension,400mg,54,Male,Yes,No
248,Cough,15mg,38,Female,Yes,Yes
249,Muscle pain,2mg,69,Male,No,Yes

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
# Preprocess the dataset
import re
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])
data['Diagnosis Hypertension'] = le.fit_transform(data['Diagnosis Hypertension'])
data['Diagnosis Diabetes'] = le.fit_transform(data['Diagnosis Diabetes'])
data['Dosage'] = data['Dosage'].astype(str).apply(lambda x: float(re.findall('\d+', x)[0]))
data

,Disease Type,Dosage,Age,Sex,Diagnosis Diabetes,Diagnosis Hypertension
0,Fever,250.0,45,1,0,1
1,Diabetes,850.0,60,0,1,0
2,Hypertension,400.0,55,1,0,1
3,Headache,50.0,77,1,1,1
4,Thyroid,100.0,38,0,0,0
...,...,...,...,...,...,...
245,Diabetes,850.0,62,0,1,1
246,Vomiting,8.0,47,0,1,1
247,Hypertension,400.0,54,1,1,0
248,Cough,15.0,38,0,1,1
249,Muscle pain,2.0,69,1,0,1

In [ ]:
# Split the dataset into training and testing sets
X = data.drop(['Disease Type'], axis=1)
y = data['Disease Type']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rn=RandomForestClassifier()
model = rn.fit(X_train, y_train)

In [ ]:
# Predict the medication type for the testing set
y_pred = model.predict(X_test)
y_pred

array(['Gastroesophageal reflux', 'Diarrhea', 'Cold fever',
       'Hypertension', 'Cold', 'Hypertension', 'Ear pain', 'Cold',
       'Vomiting', 'Hypertension', 'Cold', 'Cold fever', 'Muscle pain',
       'Diabetes', 'Hypertension', 'Diabetes', 'Abdominal pain',
       'Hypertension', 'Diarrhea', 'Diabetes', 'Hypertension',
       'Dry cough', 'Diabetes', 'Dry cough', 'Headache', 'Fever',
       'Cold fever', 'Hypertension', 'Headache', 'Diabetes',
       'Gastroesophageal reflux', 'Fever', 'Diabetes', 'Muscle pain',
       'Hypertension', 'Abdominal pain', 'Thyroid', 'Hypertension',
       'Muscle pain', 'Dry cough', 'Headache', 'Diarrhea', 'Hypertension',
       'Hypertension', 'Vomiting', 'Diabetes', 'Dry cough',
       'Abdominal pain', 'Muscle pain', 'Dry cough'], dtype=object)

In [ ]:
# Evaluate the model performance
acc= accuracy_score(y_test, y_pred)
print('Accuracy:',acc)

Accuracy: 0.7